CREATE TABLE IF NOT EXISTS public.settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key text NOT NULL UNIQUE,
  value text NOT NULL,
  created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

-- Allow public read access (needed for the website to fetch settings)
CREATE POLICY "Allow public read access" ON public.settings
  FOR SELECT USING (true);

INSERT INTO public.settings (key, value)
VALUES ('growth_consulting_video_url', 'https://www.youtube.com/watch?v=Uh0XxtYwf9k')
ON CONFLICT (key) DO NOTHING;
