-- Seed data captured from https://consult4sales.com on 2026-06-30.
-- Run after supabase-schema.sql. Uses external consult4sales URLs for existing PDFs/pages.

alter table public.courses add column if not exists video_path text;
alter table public.blogs add column if not exists video_path text;

insert into public.courses (
  slug,
  title,
  subtitle,
  description,
  duration,
  mode,
  level,
  price_label,
  cta_label,
  cta_url,
  highlights,
  sort_order,
  is_published
) values
(
  'sales-baptism',
  'Sales Baptism',
  'Sales training program for beginners',
  'Sales Baptism is curated for sales freshers and beginners. It covers discovering the sales function, fears and apprehensions, stress in sales, and sales leadership through prerecorded learning and workbooks.',
  '3 modules',
  'Virtual',
  'Beginner',
  'Rs. 999',
  'Buy Course',
  'https://consult4sales.com/sales-baptism',
  array['Discovering Sales Function', 'Fears, Apprehensions and Stress', 'Sales Leadership', 'Workbooks with prerecorded videos'],
  1,
  true
),
(
  'sales-marathon',
  'Sales Marathon',
  'Condensed online sales management course',
  'Sales Marathon focuses on the how of sales through a seven-day practical learning format. It helps salespeople understand lead generation, sales pitch, need analysis, objection handling, negotiation, and customer lifetime value.',
  '7 days',
  'Virtual / prerecorded',
  '0-10 years sales experience',
  'Rs. 2,999',
  'Buy Course',
  'https://consult4sales.com/sales-marathon',
  array['7 prerecorded videos', 'Workbook-led practice', 'Lead generation', 'Sales pitch and negotiation', 'Customer lifetime value'],
  2,
  true
),
(
  'sales-manedge',
  'Sales ManEdge',
  'Online course for new sales managers',
  'Sales ManEdge is curated for salespeople who have moved into sales management. It covers sales management process, CRM, market sensing, Ansoff Matrix, team motivation, forecasting, MIS, and customer relationship management.',
  '7 videos',
  'Virtual / prerecorded',
  'Sales Managers',
  'Rs. 2,999',
  'Buy Course',
  'https://consult4sales.com/sales-manedge',
  array['Sales management process', 'CRM and relationship skills', 'Demand forecasting', 'Sales MIS', 'Team motivation'],
  3,
  true
),
(
  'sales-ki-pathshala',
  'Sales Ki Pathshala',
  'Weekly live sales training school',
  'Sales Ki Pathshala is a weekly virtual sales training school for CEOs, entrepreneurs, and sales managers. It covers sales topics such as prospecting, lead generation, pitching, objections, negotiation, CRM, customer loyalty, and retention.',
  '25 sessions',
  'Live Zoom',
  'Entrepreneurs / CEOs / Sales Managers',
  'Rs. 4,999',
  'Buy Course',
  'https://consult4sales.com/sales-ki-pathshala',
  array['Every Wednesday', 'Live interaction', 'Toolkits and downloadable content', 'Sales and marketing topics', 'One-to-one contact option'],
  4,
  true
),
(
  'sales-ki-jaat',
  'Sales Ki Jaat',
  'Install the DNA of sales in the team',
  'Sales Ki Jaat helps sales teams acquire the DNA of sales so they overcome fear of failure, fear of rejection, fear of asking questions, and build confidence in pitching and closing.',
  null,
  'Consulting / training',
  'Sales Teams',
  'Custom proposal',
  'Enquire Now',
  'https://consult4sales.com/sales-ki-jaat',
  array['Sales DNA', 'Confidence building', 'Positive sales pitch', 'Sales closing mindset', 'Training need analysis'],
  5,
  true
),
(
  'sales-ki-vidhi',
  'Sales Ki Vidhi',
  'Sales process and sales funnel program',
  'Sales Ki Vidhi answers how to sell by focusing on sales lifecycle, process, methods, techniques, funnel ratios, and frameworks such as Action Selling, PEAK, SPANCO, and SPACER.',
  null,
  'Consulting / training',
  'Sales Teams and Managers',
  'Custom proposal',
  'Enquire Now',
  'https://consult4sales.com/sales-ki-vidhi',
  array['Sales lifecycle', 'TOFU MOFU BOFU', 'Lead generation', 'Objection handling', 'Sales closing'],
  6,
  true
),
(
  'sales-ki-niti',
  'Sales Ki Niti',
  'Sales strategy and planning',
  'Sales Ki Niti focuses on sales planning, sales techniques, strategic selling process, and winning sales strategy for improving sales outcomes.',
  null,
  'Consulting / training',
  'Owners and Sales Leaders',
  'Custom proposal',
  'Enquire Now',
  'https://consult4sales.com/sales-ki-niti',
  array['Sales strategy', 'Sales planning', 'Strategic selling', 'Process optimization', 'Winning techniques'],
  7,
  true
),
(
  'sales-mein-molbhav',
  'Sales Mein Molbhav',
  'Sales negotiation skills',
  'Sales Mein Molbhav focuses on the sales negotiation process, negotiation skills, negotiation tactics, bargaining skills, and value protection in sales management.',
  null,
  'Consulting / training',
  'Sales Teams',
  'Custom proposal',
  'Enquire Now',
  'https://consult4sales.com/sales-mein-molbhav',
  array['Negotiation process', 'Price objection handling', 'Value protection', 'Bargaining skills', 'Sales closing'],
  8,
  true
),
(
  'sales-katha',
  'Sales Katha',
  'Storytelling for sales',
  'Sales Katha explains how storytelling helps customers understand the science of sales. It supports FAB and FAQ communication with stories that make selling more relatable.',
  null,
  'Consulting / training',
  'Sales Professionals',
  'Custom proposal',
  'Enquire Now',
  'https://consult4sales.com/sales-katha',
  array['Storytelling', 'FAB communication', 'Customer understanding', 'Practical selling', 'Sales conversations'],
  9,
  true
),
(
  'sales-ke-rishte',
  'Sales Ke Rishte',
  'Customer relationship management system',
  'Sales Ke Rishte is a proprietary customer relationship management system focused on customer relationship tools and customer lifetime value.',
  null,
  'Consulting / training',
  'Sales and CRM Teams',
  'Custom proposal',
  'Enquire Now',
  'https://consult4sales.com/sales-ke-rishte',
  array['CRM system', 'Customer lifetime value', 'Relationship management', 'Retention', 'Customer farming'],
  10,
  true
)
on conflict (slug) do update set
  title = excluded.title,
  subtitle = excluded.subtitle,
  description = excluded.description,
  duration = excluded.duration,
  mode = excluded.mode,
  level = excluded.level,
  price_label = excluded.price_label,
  cta_label = excluded.cta_label,
  cta_url = excluded.cta_url,
  highlights = excluded.highlights,
  sort_order = excluded.sort_order,
  is_published = excluded.is_published;

insert into public.blogs (
  slug,
  title,
  excerpt,
  content,
  author,
  category,
  read_time_minutes,
  is_featured,
  sort_order,
  is_published
) values
(
  'why-sales-training-cannot-be-skipped',
  'Why Sales Training Cannot Be Skipped',
  'Sales training becomes costly when it is skipped because teams lose confidence, process discipline, and measurable selling behaviour.',
  'Consult4Sales describes sales training as expensive only when it is not taken. A trained salesperson understands the function of sales, handles fear and rejection better, asks better questions, and converts learning into field action. The practical approach combines role clarity, sales process, sales pitch, need analysis, objection handling, and review discipline.',
  'Strategic Concepts',
  'Sales Training',
  3,
  true,
  1,
  true
),
(
  'sales-dna-and-the-confidence-to-sell',
  'Sales DNA and the Confidence to Sell',
  'Sales Ki Jaat positions sales DNA as a learnable capability that reduces fear and improves pitching and closing.',
  'The Sales Ki Jaat program explains that the DNA of sales is not available by birth; it is acquired through training and practice. The program focuses on reducing fear of failure, fear of rejection, fear of asking questions, and fear of challenging self. The outcome is a more confident salesperson with stronger sales pitch and closing behaviour.',
  'Strategic Concepts',
  'Sales Skills',
  4,
  false,
  2,
  true
),
(
  'how-a-defined-sales-process-improves-conversion',
  'How a Defined Sales Process Improves Conversion',
  'Sales Ki Vidhi focuses on the journey from lead generation to closure through funnel ratios and repeatable sales process design.',
  'A sales process answers how to sell. Consult4Sales frames this through the sales lifecycle and the movement from top of funnel to middle of funnel and bottom of funnel. The process covers lead generation, warm lead engagement, sales pitch, objections, proposals, negotiation, closure, and customer lifetime value.',
  'Strategic Concepts',
  'Sales Process',
  4,
  false,
  3,
  true
),
(
  'growth-consulting-for-sme-and-msme-sales',
  'Growth Consulting for SME and MSME Sales',
  'SME and MSME growth depends on a complete sales ecosystem, winning teams, technology enablement, and strategy.',
  'Consult4Sales works with SME and MSME businesses to improve sales performance by leveraging the opportunities already present in their business landscape. The consulting areas include sales ecosystem design, customer persona, lead magnets, value bombs, sales process, sales kit, sales metrics, negotiation process, CRM, MIS, business analytics, KRA, KPI, and go-to-market planning.',
  'Strategic Concepts',
  'Growth Consulting',
  5,
  false,
  4,
  true
),
(
  'sales-negotiation-is-more-than-discounting',
  'Sales Negotiation Is More Than Discounting',
  'Sales Mein Molbhav treats negotiation as a structured sales management capability, not only price bargaining.',
  'In sales management, negotiation is a special process that includes skills, tactics, bargaining behaviour, objection handling, and value protection. A salesperson must understand when to propose, how to respond to price pressure, and how to close without weakening the value of the solution.',
  'Strategic Concepts',
  'Negotiation',
  3,
  false,
  5,
  true
)
on conflict (slug) do update set
  title = excluded.title,
  excerpt = excluded.excerpt,
  content = excluded.content,
  author = excluded.author,
  category = excluded.category,
  read_time_minutes = excluded.read_time_minutes,
  is_featured = excluded.is_featured,
  sort_order = excluded.sort_order,
  is_published = excluded.is_published;

insert into public.downloads (
  slug,
  title,
  description,
  category,
  file_path,
  thumbnail_path,
  file_type,
  button_label,
  sort_order,
  is_published
) values
(
  'sales-management-audit-system-checklist',
  'Sales Management Audit System Checklist',
  'A five-page checklist covering sales kit, DSR, sales policy, MIS, sales process, market intelligence, CRM, customer centricity, reference selling, cross selling, dashboard management, and service recovery.',
  'Checklist',
  'https://consult4sales.com/pdf/sales-checklist/Sales-Management-Audit-System-Check-List-1-converted.pdf',
  null,
  'PDF',
  'Download Checklist',
  1,
  true
),
(
  'lead-assessment-direct-selling-checklist',
  'Checklist for Lead Assessment in Direct Selling',
  'Checklist resource for assessing leads in a direct selling model.',
  'Checklist',
  'https://consult4sales.com/pdf/sales-checklist/Checklist-001A.pdf',
  null,
  'PDF',
  'Download Checklist',
  2,
  true
),
(
  'annual-sales-planning-workbook',
  'Annual Sales Planning Workbook',
  'Workbook resource for annual sales planning.',
  'Workbook',
  'https://consult4sales.com/pdf/sales-workbook/Workbook-for-Annual-Sales-Planning.pdf',
  null,
  'PDF',
  'Download Workbook',
  3,
  true
),
(
  'sales-workbooks',
  'Sales Workbooks Collection',
  'Collection of workbooks including annual sales planning, rural marketing, capacity building, counselors, sales negotiations, lead generation, sales closing, ownership cost, CEO role in sales management, and sales audit system.',
  'Workbook',
  'https://consult4sales.com/sales-workbooks',
  null,
  'Page',
  'View Workbooks',
  4,
  true
),
(
  'sales-checklists',
  'Sales Checklists Collection',
  'Collection of checklists for lead assessment, sales management audit, FMCG sales managers, SME CEO sales management, distributor tracking, customer complaints, need analysis, sales training, and channel distribution.',
  'Checklist',
  'https://consult4sales.com/sales-checklist',
  null,
  'Page',
  'View Checklists',
  5,
  true
),
(
  'strategic-concepts-brochure',
  'Strategic Concepts Brochure',
  'Complete Strategic Concepts brochure available from the Consult4Sales downloads section.',
  'Brochure',
  'https://consult4sales.com/img/brochure/STRATEGIC-CONCEPT-BROCHURE-2019-FINAL.pdf',
  null,
  'PDF',
  'Download Brochure',
  6,
  true
),
(
  'client-testimonials',
  'Client Testimonials',
  'Client appreciation and testimonial collection for sales training and consulting work.',
  'Testimonials',
  'https://consult4sales.com/testimonial',
  null,
  'Page',
  'View Testimonials',
  7,
  true
),
(
  'linkedin-recommendations',
  'LinkedIn Recommendations',
  'Professional recommendations and endorsements for Sanjay Singh and Strategic Concepts.',
  'Recommendations',
  'https://consult4sales.com/recommendations',
  null,
  'Page',
  'View Recommendations',
  8,
  true
)
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  category = excluded.category,
  file_path = excluded.file_path,
  thumbnail_path = excluded.thumbnail_path,
  file_type = excluded.file_type,
  button_label = excluded.button_label,
  sort_order = excluded.sort_order,
  is_published = excluded.is_published;
